# path (from the repository root) to sample sheet (csv format, columns: sample, condition, ...)
samples_sheet: config/samples_sheet.csv

# perform trimming: false or true
# if true go to params (at the end)
# to set desired trimming parameters
trimming: false

aligner: bowtie

resources:
  ref:
    index: "index_bowtie"
    # Ensembl species name
    species: homo_sapiens
    # Ensembl release
    release: 101
    # Genome build
    build: GRCh38
  ref_spike:
    # Ensembl species name
    species: drosophila_melanogaster 
    # Ensembl release
    release: 110
    # Genome build
    build: dm6


params:
  fastp-pe: ""
  fastp-se: ""
  bowtie: 
    global: "--chunkmbs 1024 -m 1 --best -S --no-unal -q"
    pe: "-I 10 -X 1000"

  samtools:
  # Memory used by every core of samtools (GB). Be careful that 
  # memory x threads is not bigger than the amount of memory assigned to align rule
    memory: 2

threads:
  fastp:
    10
  bowtie: 
    10
  