# path (from the repository root) to sample sheet (csv format, columns: sample, condition, ...)
samples_sheet: config/samples_sheet.csv

#if needed, specify an output folder
#the default is the snakemake working directory
output_path: ""

# perform trimming: false or true
# if true go to params (at the end)
# to set desired trimming parameters
trimming: true

aligner: bowtie

#type of normalization to perform to generate the bigwig files (one from RAW, Orlando , RX-Input)
normalization_type: "RX-Input"

resources:
  ref: 
    #if bowtie index is not available leave only "" , it will be created
    #otherwise proved the path to the folder containing bowtie index (and add the name of the index after the path)
    index: "data/subset_GRCh38_bowtieIndex/subset_GRCh38_bowtieIndex"
    # Ensembl species name
    species: homo_sapiens
    # Ensembl release
    release: 101
    # Genome build
    build: GRCh38 
    #blacklist regions (from https://github.com/Boyle-Lab/Blacklist/tree/master/lists)
    blacklist: "data/hg38-blacklist.v2.bed"

  ref_spike:
    #if bowtie index is not avialable leave only "" , it will be created
    #otherwise proved the path to the folder containing bowtie index
    index_spike: "data/dm6_index/bowtie1_dm6_index"
    # Ensembl species name
    species: drosophila_melanogaster 
    # Ensembl release
    release: 110
    # Genome build
    build: BDGP6.46

params:
  fastp-pe: ""
  fastp-se: ""
  bowtie: 
    global: "--chunkmbs 1024 -m 1 --best -S --no-unal -q"
    pe: "-I 10 -X 1000"

  samtools:
    # Memory used by every core of samtools (GB). Be careful that 
    # memory x threads is not bigger than the amount of memory assigned to align rule
    memory: 1
  deeptools:
    #change this according to: https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
    effective_genome_length: 11000000
    #read extension, only for SE
    read_extension: 75
  peakCalling:
    chrom_sizes: "data/hg38.chromsizes"
    macs2:
      pvalue: 0.05
    epic2:
      #effective genome fraction, change this according to https://github.com/biocore-ntnu/epic2/blob/master/epic2/effective_sizes/hg38_50.txt
      # in the github it is indicated as Effective genome size, and you need to know the read length in  order to set it
      egf: 0.869 
      fdr: 0.05
    edd:
      fdr: 0.05


threads:
  fastp:
    10
  bowtie: 
    10
  
