$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples_sheet:
    type: string
  trimming:
    type: boolean
  
  aligner:
    type: string
    enum:
        - 'bowtie2'
  normalization_type:
    type: string
    enum: 
        - RAW
        - Orlando
        - RX-Input
  diffPeakAnalysis:
    type: object
    properties:
      perform_diff_analysis:
        type: boolean
      contrasts:
        type: object
        additionalProperties:
          type: array
          items:
            type: string
            minItems : 1
      padjust:
        type: number
      log2FCcutoff:
        type: number

  resources:
    type: object
    properties:
      ref:
        type: object
        properties:
          index:
            type: string
          assembly:
            type: string
            enum:
              - mm9
              - mm10
              - hg19
              - hg38
      ref_spike:
        type: object
        properties:
          spike_assembly:
            type: string
            enum:
              - dm3
              - dm6
              - mm10
              - mm9
              - hg19
              - hg38
              - hs1


# entries that have to be in the config file for successful validation
required:
  - samples_sheet
  - trimming

