$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples_sheet:
    type: string
  trimming:
    type: boolean
  
  aligner:
    type: string
    enum:
        - 'bowtie'
  normalization_type:
    type: string
    enum: 
        - RAW
        - Orlando
        - RX-Input

  resources:
    type: object
    properties:
      ref:
        type: object
        properties:
          assembly:
            type: string
            enum:
              - mm9
              - mm10
              - hg19
              - hg38

# entries that have to be in the config file for successful validation
required:
  - samples_sheet
  - trimming

